version: '3.9'

x-omnistrate-service-plan:
  tenancyType: 'OMNISTRATE_MULTI_TENANCY'

x-customer-integrations:
  logs:
  metrics:

services:
  gpuinfo:
    image: ghcr.io/omnistrate-community/gpu-slicing-example:0.0.2
    ports:
      - 5000:5000
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '100m'
          memory: 50M
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        defaultValue: g4dn.xlarge
        modifiable: true
        required: true
        export: true
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
    x-omnistrate-capabilities:
      autoscaling:
        maxReplicas: 3
        minReplicas: 1
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
      serverlessConfiguration:
        targetPort: 5000
        enableAutoStop: true
        minimumNodesInPool: 1

