version: '3.9'

# x-omnistrate-my-account:
#   AwsAccountId: "<YOUR ACCOUNT ID>"
#   AwsBootstrapRoleAccountArn: arn:aws:iam::<YOUR ACCOUNT ID>:role/omnistrate-bootstrap-role

x-omnistrate-service-plan:
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY' 

services:
  gpuinfo:
    image: ghcr.io/omnistrate-community/gpu-slicing-example:0.0.3
    ports:
      - 5000:5000
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '100m'
          memory: 50M
    x-omnistrate-capabilities:
      autoscaling: 
        maxReplicas: 3 # for production set to your desired maximum (for dev we want to keep it low)
        minReplicas: 1 # for production set to your desired minimum
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
      serverlessConfiguration:
        targetPort: 5000
        enableAutoStop: true
        minimumNodesInPool: 1 # for production set to your desired warm pool size (for dev we want to keep it low)
    x-omnistrate-compute: # required for dedicated
      instanceTypes:
        - cloudProvider: aws
          name: g4dn.xlarge