version: '3.9'

# UNCOMMENT: Set your account id
# x-omnistrate-my-account:
#   AwsAccountId: "<YOUR ACCOUNT ID>"
#   AwsBootstrapRoleAccountArn: arn:aws:iam::<YOUR ACCOUNT ID>:role/omnistrate-bootstrap-role

x-omnistrate-service-plan:
  name: 'gpu-slicing-example hosted tier' 
  tenancyType: 'OMNISTRATE_MULTI_TENANCY' 

x-internal-integrations: 
  multiTenantGpu: 
    instanceType: g4dn.xlarge # instance type to be used for GPU slicing
    timeSlicingReplicas: 2 # number of replicas to be used for time slicing

services:
  gpuinfo:
    image: ghcr.io/omnistrate-community/gpu-slicing-example:0.0.3
    ports:
      - 5000:5000
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '100m'
          memory: 50M
    x-omnistrate-capabilities:
      autoscaling: 
        maxReplicas: 3 # for production set to your desired maximum (for dev we want to keep it low)
        minReplicas: 1 # for production set to your desired minimum
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
      serverlessConfiguration:
        targetPort: 5000
        enableAutoStop: true
        minimumNodesInPool: 1 # for production set to your desired warm pool size (for dev we want to keep it low)